robonomics_market/src/robonomics_market/matcher.py
Let matcher log be more informative and less messy.
Not tested.
=> Pretty matcher output

robonomics_market/src/robonomics_market/matcher.py
=> Little fix

robonomics_control/src/robonomics_control/distribution.py
We need a service to clean up outdated data.
There is also 3 sec delay before first market update to let other nodes init.
=> Robot distribution reset service

robonomics_lighthouse/src/robonomics_lighthouse/infochan.py, robonomics_lighthouse/src/robonomics_lighthouse/messageConverter.py
robonomics_lighthouse: Add validation for ipfs messages using voluptuous
=> robonomics_lighthouse: validate messages

robonomics_liability/launch/liability.launch, robonomics_liability/src/robonomics_liability/executor.py
Real drones have a lot of topics with many messages. Convenient to have feature to choose topics, which record for result of liability.
=> Choose executor result topics

nix/liability.nix, nix/lighthouse.nix, robonomics_liability/src/robonomics_liability/player.py, robonomics_liability/src/robonomics_liability/test/test_executor.py, robonomics_liability/src/robonomics_liability/test/test_player.py, robonomics_liability/src/robonomics_liability/test/test_recorder.py, robonomics_liability/tests/liability.test, robonomics_lighthouse/src/robonomics_lighthouse/infochan.py, robonomics_lighthouse/src/robonomics_lighthouse/lighthouse.py, robonomics_lighthouse/src/robonomics_lighthouse/pubsub.py, robonomics_lighthouse/src/robonomics_lighthouse/test/test_infochan.py, robonomics_lighthouse/src/robonomics_lighthouse/test/test_signer.py
launch with:
rostest -r robonomics_liability liability.test --text
=> use ipfsapi in pubsub and tests improvements

robonomics_liability/src/robonomics_liability/executor.py, robonomics_liability/src/robonomics_liability/player.py
Fix for https://github.com/airalab/robonomics_comm/issues/30
=> do not play objective if it's not a rosbag file

robonomics_liability/src/robonomics_liability/finalization_checker.py, robonomics_liability/src/robonomics_liability/listener.py
=> add topic with finalized liability addresses

ethereum_common/src/ethereum_common/eth_keyfile_helper.py, robonomics_liability/launch/liability.launch, robonomics_liability/src/robonomics_liability/executor.py, robonomics_lighthouse/src/robonomics_lighthouse/pubsub.py, robonomics_lighthouse/src/robonomics_lighthouse/signer.py
possible fixes for #38 and #39
=> use local key in liability exector and pubsub improvements

robonomics_liability/CMakeLists.txt, robonomics_liability/src/robonomics_liability/LiabilityExecutionThread.py, robonomics_liability/src/robonomics_liability/executor.py, robonomics_liability/src/robonomics_liability/listener.py, robonomics_liability/src/robonomics_liability/player.py, robonomics_liability/src/robonomics_liability/recorder.py, robonomics_liability/src/robonomics_liability/test/test_executor.py, robonomics_liability/src/robonomics_liability/test/test_recorder.py, robonomics_liability/srv/FinishLiability.srv, robonomics_liability/srv/StartLiability.srv
=> Add an ability to process several liability contracts simultaneously by the executor

ethereum_common/CMakeLists.txt, ethereum_common/launch/signer.launch, ethereum_common/scripts/signer_node, ethereum_common/src/ethereum_common/erc20_services.py, ethereum_common/src/ethereum_common/nodes.py, ethereum_common/src/ethereum_common/signer.py, robonomics_liability/launch/liability.launch, robonomics_liability/src/robonomics_liability/listener.py, robonomics_liability/src/robonomics_liability/test/test_executor.py, robonomics_liability/tests/liability.test, robonomics_lighthouse/CMakeLists.txt, robonomics_lighthouse/launch/infochan.launch, robonomics_lighthouse/launch/lighthouse.launch, robonomics_lighthouse/src/robonomics_lighthouse/infochan.py, robonomics_lighthouse/src/robonomics_lighthouse/nodes.py, robonomics_lighthouse/src/robonomics_lighthouse/test/test_infochan.py, robonomics_lighthouse/src/robonomics_lighthouse/test/test_signer.py, robonomics_lighthouse/tests/lighthouse.test
=> move signer node to ethereum_common

ethereum_common/launch/erc20.launch, ethereum_common/launch/signer.launch, ipfs_common/launch/ipfs_channel.launch, robonomics_control/launch/control.launch, robonomics_liability/launch/liability.launch, robonomics_lighthouse/launch/lighthouse.launch
airalab/aira#59 airalab/aira#65
=> respawn nodes on unhandled exceptions

robonomics_liability/src/robonomics_liability/LiabilityExecutionThread.py
=> start recorder before getting objective

robonomics_liability/msg/Liability.msg, robonomics_liability/src/robonomics_liability/listener.py
=> Add lighthouse field to Liability.msg

ethereum_common/launch/erc20.launch, ethereum_common/src/ethereum_common/erc20_services.py, ethereum_common/src/ethereum_common/eth_services.py, ethereum_common/src/ethereum_common/eth_utils.py, robonomics_liability/tests/liability.test, robonomics_liability/tests/test_executor.py
=>  use web3 ws provider in ethereum_common services

robonomics_liability/CMakeLists.txt, robonomics_liability/launch/liability.launch, robonomics_liability/scripts/persistence_node, robonomics_liability/src/robonomics_liability/LiabilityExecutionThread.py, robonomics_liability/src/robonomics_liability/LiabilityExecutionsPersistence.py, robonomics_liability/src/robonomics_liability/executor.py, robonomics_liability/src/robonomics_liability/listener.py, robonomics_liability/src/robonomics_liability/nodes.py, robonomics_liability/src/robonomics_liability/player.py, robonomics_liability/srv/PersistenceContainsLiability.srv
=> Introduced persistence service for liabilities

ethereum_common/launch/signer.launch, ethereum_common/src/ethereum_common/signer.py, ipfs_common/src/ipfs_common/ipfs_channel.py, robonomics_liability/abi/factory.json, robonomics_liability/abi/liability.json, robonomics_liability/launch/liability.launch, robonomics_liability/tests/liability.test, robonomics_liability/tests/testMessages.py, robonomics_liability/tests/test_executor.py, robonomics_liability/tests/test_signer.py, robonomics_msgs/msg/Demand.msg, robonomics_msgs/msg/Offer.msg, robonomics_msgs/src/robonomics_msgs/messageValidator.py, robonomics_msgs/src/robonomics_msgs/robonomicsMessageUtils.py
related to airalab/robonomics_contracts#53
Currently factory is required in signer node for getting nonce field by address
Also additional signers launches on tests: demand and offer signed by different keys
=> Demand/Offer: reducing nonce field and add sender

ethereum_common/msg/_UInt256.py.patch
=> Comparison operators for UInt256

robonomics_liability/CMakeLists.txt, robonomics_liability/tests/liability.test, robonomics_liability/tests/test_ethereum_common_messages.py
=> Add tests for UInt256 arithmetic and comparison

ipfs_common/CMakeLists.txt, ipfs_common/msg/Filepath.msg, ipfs_common/src/ipfs_common/ipfs_channel.py, ipfs_common/src/ipfs_common/ipfs_fileutils.py, ipfs_common/srv/IpfsDownloadFile.srv, ipfs_common/srv/IpfsUploadFile.srv, robonomics_liability/src/robonomics_liability/LiabilityExecutionThread.py
=> Introducing ROS API for IPFS

ipfs_common/src/ipfs_common/ipfs_channel.py, robonomics_msgs/msg/Demand.msg, robonomics_msgs/msg/Offer.msg, robonomics_msgs/src/robonomics_msgs/messageValidator.py
This version is not finished. 
It is able to recieve and parse correctly Demand/Offer, but is not able to send
=> Added nonce for feedback compatibility

ethereum_common/src/ethereum_common/signer.py, fetchNixpkgs.nix, robonomics_liability/tests/testMessages.py, robonomics_liability/tests/test_executor.py, robonomics_liability/tests/test_messageValidator.py, robonomics_msgs/src/robonomics_msgs/messageValidator.py, robonomics_msgs/src/robonomics_msgs/robonomicsMessageUtils.py
=> Add ENS support for message hashers

ethereum_common/src/ethereum_common/signer.py, ipfs_common/src/ipfs_common/ipfs_channel.py, robonomics_liability/tests/test_executor.py, robonomics_liability/tests/test_infochan.py, robonomics_liability/tests/test_signer.py, robonomics_msgs/src/robonomics_msgs/messageValidator.py, robonomics_msgs/src/robonomics_msgs/robonomicsMessageUtils.py
=> robonomics messages validation improvements

ipfs_common/src/ipfs_common/ipfs_rosbag.py
=> ipfs utils improvements

aira_graph/src/aira_graph/nodes.py, ethereum_common/src/ethereum_common/nodes.py, ipfs_common/src/ipfs_common/ipfs_channel.py, ipfs_common/src/ipfs_common/nodes.py, robonomics_control/src/robonomics_control/nodes.py, robonomics_liability/src/robonomics_liability/nodes.py, robonomics_liability/tests/testMessages.py, robonomics_liability/tests/test_infochan.py, robonomics_liability/tests/test_messageValidator.py, robonomics_msgs/CMakeLists.txt, robonomics_msgs/msg/AddedOrderFeedback.msg, robonomics_msgs/msg/AddedPendingTransactionFeedback.msg, robonomics_msgs/src/robonomics_msgs/messageValidator.py, robonomics_msgs/src/robonomics_msgs/robonomicsMessageUtils.py
=> added Feedback messages support

robonomics_liability/CMakeLists.txt, robonomics_liability/src/robonomics_liability/executor.py, robonomics_liability/src/robonomics_liability/listener.py, robonomics_liability/srv/ReadLiability.srv, robonomics_liability/tests/test_messageValidator.py, robonomics_msgs/src/robonomics_msgs/robonomicsMessageUtils.py
=> Execute arbitrary liability by address

aira_graph/src/aira_graph/aira_graph.py, default.nix, fetchNixpkgs.nix, ipfs_common/src/ipfs_common/ipfs_channel.py, ipfs_common/src/ipfs_common/ipfs_common.py, ipfs_common/src/ipfs_common/pubsub.py, robonomics_liability/src/robonomics_liability/executor.py, robonomics_liability/src/robonomics_liability/player_service.py, robonomics_liability/tests/test_executor.py
=> use ipfshttpclient

robonomics_liability/src/robonomics_liability/LiabilityExecutionsPersistence.py, robonomics_liability/src/robonomics_liability/executor.py, robonomics_liability/src/robonomics_liability/listener.py, robonomics_liability/srv/FinishLiability.srv, robonomics_liability/srv/PersistenceContainsLiability.srv, robonomics_liability/srv/ReadLiability.srv, robonomics_liability/srv/StartLiability.srv, robonomics_liability/tests/test_executor.py
=> use Address type

aira_graph/src/aira_graph/aira_graph.py, default.nix, ipfs_common/launch/ipfs_channel.launch, ipfs_common/src/ipfs_common/ipfs_channel.py, ipfs_common/src/ipfs_common/ipfs_common.py, ipfs_common/src/ipfs_common/ipfs_fileutils.py, ipfs_common/src/ipfs_common/pubsub.py, robonomics_liability/launch/liability.launch, robonomics_liability/src/robonomics_liability/LiabilityExecutionThread.py, robonomics_liability/src/robonomics_liability/executor.py, robonomics_liability/src/robonomics_liability/listener.py, robonomics_liability/src/robonomics_liability/player_service.py, robonomics_liability/tests/test_executor.py
related to https://github.com/airalab/autonomous_agent_template/issues/7
=> IPFS communication improvements

ethereum_common/CMakeLists.txt, ethereum_common/msg/TxHash.msg, robonomics_liability/tests/testMessages.py, robonomics_msgs/msg/AddedPendingTransactionFeedback.msg, robonomics_msgs/src/robonomics_msgs/robonomicsMessageUtils.py
=> change added_pending_transaction format

fetchNixpkgs.nix, ipfs_common/src/ipfs_common/ipfs_rosbag.py
Motivation:
Extend IpfsRosBag with rospy.Bag metainfo
Allow get meta data via `.bag` field
=> Add Bag as return parameter for meta information
